import { type RegistrationFormState } from "./registration-types.js";

export const acquisitionChannelOptions = [
  "Venta directa",
  "Referidos",
  "WhatsApp",
  "Sitio web / SEO",
  "Google Ads",
  "Meta Ads",
  "LinkedIn",
  "Outbound",
  "Email",
  "Aliados",
  "Distribuidores",
  "Marketplace",
  "Retail / punto físico",
  "Ferias / eventos",
];

export const emptyRegistrationForm: RegistrationFormState = {
  profileName: "",
  profileEmail: "",
  profileRole: "",
  profileArea: "",
  profileCountry: "",
  peopleManaged: "",
  companyName: "",
  sectorCategory: "",
  employeeCount: "",
  yearsInMarket: "",
  operatingCountries: "",
  sellsTo: "",
  revenueModel: "",
  website: "",
  acquisitionChannels: [],
  averageTicket: "",
  averageSalesCycleDays: "",
  competitor1: "",
  competitor1Web: "",
  competitor2: "",
  competitor2Web: "",
  competitor3: "",
  competitor3Web: "",
  categoryNotes: "",
  documents: "",
};
